/* Script to create the original structure of the databases */

CREATE TABLE `T_GROUPS` (
	`GROUPS_ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`GROUPS_NAME`	TEXT NOT NULL,
	`GROUPS_DESCRIPTION`	TEXT
);
CREATE TABLE `T_PLAYERS` (
	`PLAYERS_ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`PLAYERS_LASTNAME`	TEXT NOT NULL,
	`PLAYERS_FIRSTNAME`	TEXT NOT NULL,
	`PLAYERS_NICKNAME`	TEXT,
	`PLAYERS_TEAM`	TEXT,
	`PLAYERS_PICTURE`	BLOB
);
CREATE TABLE `T_REPLICAS` (
	`REPLICAS_ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`PLAYERS_ID`	INTEGER NOT NULL,
	`REPLICAS_NAME`	TEXT NOT NULL,
	`REPLICAS_FPS`	INTEGER,
	`REPLICATYPE_ID`	INTEGER,
	`REPLICAS_PICTURE`	TEXT,
	FOREIGN KEY(`PLAYERS_ID`) REFERENCES T_PLAYERS ( PLAYERS_ID ) ON DELETE CASCADE
);
CREATE TABLE `T_PLAYERS_GROUPS_PG` (
	`PG_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`GROUPS_ID`	INTEGER NOT NULL,
	`PLAYERS_ID`	INTEGER NOT NULL,
	FOREIGN KEY(`GROUPS_ID`) REFERENCES T_GROUPS ( GROUPS_ID ) ON DELETE CASCADE,
	FOREIGN KEY(`PLAYERS_ID`) REFERENCES T_PLAYERS ( PLAYERS_ID ) ON DELETE CASCADE
);
CREATE TABLE `T_REPLICATYPE` (
	`REPLICATYPE_ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`REPLICATYPE_TYPE`	TEXT NOT NULL,
	`REPLICATYPE_POWERED_BY`	TEXT,
	`REPLICATYPE_DESCRIPTION`	TEXT
);
CREATE TABLE `T_SCRIPTS` (
	`SCRIPTS_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`SCRIPTS_NAME`	TEXT NOT NULL,
	`SCRIPTS_DESCRIPTION`	TEXT,
	`SCRIPTS_DETAILS`	TEXT
);
